---
- name: Setup system as a container host
  hosts: container_host

  tasks:
    - name: Ensure correct packages are installed
      become: true
      ansible.builtin.dnf:
        name: '@Container Management'
        state: present

    - name: Ensure correct Cockpit packages are installed if necessary
      when: enable_cockpit
      become: true
      ansible.builtin.dnf:
        name: cockpit-podman
        state: present

    - name: Enable root services
      become: true
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        enabled: true
      loop:
        - podman.service
        - podman-restart.service

    - name: Start root socket
      become: true
      ansible.builtin.systemd_service:
        name: podman.socket
        enabled: true
        state: started

    - name: Create rootful quadlet directory
      become: true
      ansible.builtin.file:
        path: "/etc/containers/systemd/"
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Ensure lingering enabled
      become: true
      ansible.builtin.command:
        cmd: "loginctl enable-linger {{ ansible_user }}"
        creates: /var/lib/systemd/linger/{{ ansible_user }}

    - name: Enable user services
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        enabled: true
        state: started
        scope: user
      loop:
        - podman.service
        - podman-restart.service

    - name: Start user services
      ansible.builtin.systemd_service:
        name: podman.socket
        enabled: true
        state: started
        scope: user

    - name: Create rootless quadlet directory
      ansible.builtin.file:
        path: "~/.config/containers/systemd/"
        state: directory
        mode: '0755'

...
