---
- name: Setup crafty container
  hosts: alderaan

  vars:
    container_name: "crafty"
    image: "registry.gitlab.com/crafty-controller/crafty-4:latest"
    ports:
      - host: 8000
        container: 8000
        proto: tcp
        firewall: true
      - host: 8123
        container: 8123
        proto: tcp
        firewall: true
      - host: 8443
        container: 8443
        proto: tcp
        firewall: true
      - host: 19132
        container: 19132
        proto: udp
        firewall: true
      - host: 25500-25600
        container: 25500-25600
        proto: tcp
        firewall: true
    volumes:
      - host_dir_name: "backups"
        container_mnt: "/crafty/backups"
        mode: '2775'
        container_uid: 1000
        container_gid: 0
      - host_dir_name: "logs"
        container_mnt: "/crafty/logs"
        mode: '2775'
        container_uid: 1000
        container_gid: 0
      - host_dir_name: "servers"
        container_mnt: "/crafty/servers"
        mode: '2775'
        container_uid: 1000
        container_gid: 0
      - host_dir_name: "config"
        container_mnt: "/crafty/app/config"
        mode: '2775'
        container_uid: 1000
        container_gid: 0
      - host_dir_name: "import"
        container_mnt: "/crafty/import"
        mode: '2775'
        container_uid: 1000
        container_gid: 0

  tasks:
    - name: Setup Crafty container
      ansible.builtin.include_role:
        name: container_service_setup

...
