---
- name: Setup nginx-proxy-manager container
  hosts: alderaan

  vars:
    container_name: "nginx-proxy-manager"
    image: "docker.io/jc21/nginx-proxy-manager:latest"
    ports:
      - host: 9080
        container: 80
        proto: tcp
        firewall: true
      - host: 9443
        container: 443
        proto: tcp
        firewall: true
      - host: 9081
        container: 81
        proto: tcp
        firewall: true
    volumes:
      - host_dir_name: "data"
        container_mnt: "/data"
        mode: '0755'
        container_uid: 0
        container_gid: 0
      - host_dir_name: "letsencrypt"
        container_mnt: "/etc/letsencrypt"
        mode: '0755'
        container_uid: 0
        container_gid: 0

  tasks:
    - name: Setup nginx-proxy-manager container
      ansible.builtin.include_role:
        name: container_service_setup

    - name: Forward port 80
      become: true
      ansible.posix.firewalld:
        port_forward:
          - port: 80
            proto: tcp
            toport: 9080
        state: enabled
        permanent: true
        immediate: true

    - name: Forward port 443
      become: true
      ansible.posix.firewalld:
        port_forward:
          - port: 443
            proto: tcp
            toport: 9443
        state: enabled
        permanent: true
        immediate: true

...
