---
- name: Inventory report
  hosts: all
  gather_facts: true
  strategy: linear

  pre_tasks:
    - name: Ensure Reports directories exist # noqa run-once[task]
      ansible.builtin.file:
        state: directory
        mode: '0755'
        path: "{{ playbook_dir }}/reports/"
      delegate_to: localhost
      run_once: true 

  tasks:
    - name: Create HTML report # noqa run-once[task]
      ansible.builtin.template:
        src: report.csv.j2
        dest: "{{ playbook_dir }}/reports/report.csv"
        mode: '0644'
      delegate_to: localhost
      run_once: true

...
