---
- name: Setup Semaphore
  hosts: alderaan

  vars:
    volume: /home/damien/semaphore/volumes/postgresql-data:/var/lib/pgsql/data:Z
    port: 3030:3000
    semaphore_image: docker.io/semaphoreui/semaphore:latest
    db_image: registry.redhat.io/rhel9/postgresql-15:latest
    secrets:
      - name: semaphore-db-pass
        value: "{{ lookup('ansible.builtin.password','/dev/null') }}"
      - name: semaphore-access-key-encryption
        value: "{{ lookup('ansible.builtin.password','/dev/null') }}"
      - name: semaphore-admin-password
        value: "{{ nonroot_user_pass }}"



  tasks:
    - name: Generate podman secrets
      containers.podman.podman_secret:
        name: item.name
        data: item.value
        state: present
      loop: "{{ secrets }}"

    - name: Create podman network
      ansible.builtin.debug:
        msg: "Unimplemented"

    - name: X
      ansible.builtin.debug:
        msg: "Unimplemented"

    - name: X
      ansible.builtin.debug:
        msg: "Unimplemented"

    - name: X
      ansible.builtin.debug:
        msg: "Unimplemented"

...
