---
- name: Setup uptime-kuma container
  hosts: container_host

  vars:
    container_name: "uptime-kuma"
    image: "docker.io/louislam/uptime-kuma:latest"
    ports:
      - host: 3001
        container: 3001
        proto: tcp
        firewall: true
    volumes:
      - host_dir_name: "data"
        container_mnt: "/app/data"

  tasks:
    - name: Setup uptime-kuma container
      ansible.builtin.include_role:
        name: container_service_setup

...
