---
# tasks file for update_packages

- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  register: update_output
  notify: "Packages updated"

- name: Check if reboot is requested
  ansible.builtin.command: dnf needs-restarting -r
  register: result
  changed_when: result.rc == 1
  failed_when: false
  notify: "Reboot requested"

...
